# Generated by Django 6.0.2 on 2026-03-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorreading",
            name="irrigation_state",
            field=models.CharField(default="OFF", max_length=10),
            preserve_default=False,
        ),
    ]
